### ISSUE TITLE
hostusers里面,增加用户的时候,有些问题.

### ISSUE THREAD

**Issue by someonebw** [triaquae/CrazyEye#4]
如果多个用户名一样的话,在列表中,看不到对应的memo,不是很方便.

**Comment by triaquae** [comment]
ok,回头加个memo显示 

## 

Alex Li/李杰

CTO ｜老男孩教育
Web: http://oldboyedu.com 

在 2015-11-02 17:25:31，"someonebw" notifications@github.com 写道：

如果多个用户名一样的话,在列表中,看不到对应的memo,不是很方便.

**Comment by someonebw** [comment]
感谢:)

**Comment by someonebw** [comment]
感谢:)
