### ISSUE TITLE
用户访问记录时间问题

### ISSUE THREAD

**Issue by someonebw** [triaquae/CrazyEye#5]
登录日期是对的,登出日期不对,感觉差了+8小时,时区是否不对?

**Comment by triaquae** [comment]
此问题会修复

## 

Alex Li/李杰

CTO ｜老男孩教育
Web: http://oldboyedu.com 

在 2015-11-04 11:08:06，"someonebw" notifications@github.com 写道：

登录日期是对的,登出日期不对,感觉差了+8小时,时区是否不对?

**Comment by someonebw** [comment]
感谢:)
